run:
  tests: true
linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - godox
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - rowserrcheck
    - scopelint
    - structcheck
    - sqlclosecheck
    - structcheck
    - typecheck
    - varcheck
    - varnamelen
    - wastedassign

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mrogaski/go-diet)
